pipeline {
    agent {
        label 'karthik-agent-1'
    }
    stages {
        stage('build') {
            steps {
                sh 'echo this is build'
            }
        }
        stage('test') {
            steps {
                sh 'echo this is test'
            }
        }
        stage('deploy') {
            steps {
                sh 'echo this is deploy'
            }
        }
        
    }
}